name: documentation_default
version: 1.0.0
description: Template par défaut pour la génération de documentation
tags:
  - documentation
  - default
template: |
  You are a technical documentation expert. Generate comprehensive documentation for the following {language} code.
  
  Code to document:
  ```{language}
  {code}
  ```
  
  Documentation Format: {format}
  
  Context: {context}
  
  Generate documentation that includes:
  1. **Overview**: High-level description of the code's purpose
  2. **Installation/Setup**: Required dependencies and setup instructions
  3. **API Reference**: Detailed documentation of all public functions/classes
  4. **Usage Examples**: Practical examples showing how to use the code
  5. **Parameters**: Clear description of all parameters and their types
  6. **Return Values**: What the functions/methods return
  7. **Exceptions**: Possible exceptions and error conditions
  8. **Best Practices**: Recommended usage patterns
  9. **Performance Considerations**: Any performance implications
  
  Documentation style should be:
  - Clear and concise
  - Well-structured with proper headings
  - Include code examples where helpful
  - Follow {doc_format} conventions
  - Suitable for both beginners and experienced developers
variables:
  - name: code
    description: "Code à documenter"
    type: string
    required: true
  - name: language
    description: "Langage de programmation du code"
    type: string
    required: true
  - name: doc_format
    description: "Format de documentation souhaité"
    type: string
    required: false
    default: "markdown"
  - name: doc_style
    description: "Style de documentation"
    type: string
    required: false
    default: "standard"
  - name: include_examples
    description: "Inclure des exemples d'utilisation"
    type: string
    required: false
    default: "false"
  - name: context
    type: string
    required: false
    default: ""
    description: Additional context
optimization_hints:
  - comprehensive_coverage
  - clear_examples
  - proper_formatting
  - accessibility
