#!/usr/bin/env python3
"""Verrous de dépendances reproductibles, dérivés de ``pyproject.toml`` (source unique).

Mécanisme : ``uv pip compile --universal --generate-hashes --exclude-newer <date>`` produit un verrou
unique par cible, valable pour Python 3.11 ET 3.12 (marqueurs d'environnement), avec les empreintes
SHA-256 de tous les fichiers distribués ; l'installation se fait avec
``pip install --require-hashes --no-deps -r locks/<cible>.txt``. ``--exclude-newer`` (date consignée
dans l'en-tête) rend la résolution rejouable : la même source donne le même verrou.

Sous-commandes (bibliothèque standard + ``packaging`` ; ``uv`` seulement pour ``generate``) :

``generate``
    Résout et réécrit ``locks/*.txt`` (réseau + uv). ``--exclude-newer`` change la date de gel.
``check``
    Hors ligne. Échoue (code 1) si, pour une cible : le verrou manque, son empreinte de source
    (``source-sha256``, calculée sur les dépendances/extras/groupes de ``pyproject.toml``) ne
    correspond plus, une entrée n'est pas épinglée ``==`` ou n'a aucune empreinte, ou une dépendance
    directe de la source est absente ou hors de son intervalle dans le verrou. ``--recompile``
    ajoute (réseau + uv) la comparaison avec une résolution fraîche à la même date de gel.
``requirements``
    Réécrit ``requirements.txt`` et ``requirements-dev.txt`` (simples inclusions des verrous).

Aucune cible n'est installée par ce script.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from packaging.markers import Marker
from packaging.requirements import InvalidRequirement, Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"
LOCK_DIR = ROOT / "locks"
HEADER_TAG = "# GENERATED by scripts/locks.py"
DEFAULT_EXCLUDE_NEWER = "2026-10-08T00:00:00Z"
PYTHON_VERSIONS = ("3.11", "3.12")  # versions exercées par la CI ; le verrou est universel (>=3.11)


@dataclass(frozen=True)
class Target:
    """Une cible de verrouillage : quelles parties de pyproject.toml entrent dans le verrou."""

    name: str
    description: str
    project_deps: bool = True
    extras: tuple[str, ...] = ()
    groups: tuple[str, ...] = ()
    # Borne basse de la résolution universelle (les images sandbox sont en 3.12).
    python_version: str = "3.11"


TARGETS: dict[str, Target] = {
    t.name: t
    for t in (
        Target("lint", "job CI « Ruff » : l'outil seul", project_deps=False, groups=("lint",)),
        Target("runtime", "image docker/collegue et déploiement (serveur MCP + dashboard)", extras=("dashboard",)),
        Target(
            "dev", "jobs CI « Pytest » : runtime + dashboard + outils de test/construction", extras=("dashboard", "dev")
        ),
        Target(
            "audit",
            "job CI « Dependency audit » : runtime + dashboard + pip-audit",
            extras=("dashboard",),
            groups=("audit",),
        ),
        Target("sandbox", "docker/sandbox/Dockerfile", project_deps=False, groups=("sandbox",), python_version="3.12"),
        Target(
            "sandbox-openhands",
            "docker/sandbox/Dockerfile.openhands (OpenHands 1.7.0, SDK/tools 1.19.1, lmnr 0.7.52)",
            project_deps=False,
            groups=("sandbox-openhands",),
            python_version="3.12",
        ),
    )
}

REQUIREMENTS_FILES = {
    "requirements.txt": "runtime",
    "requirements-dev.txt": "dev",
}


class LockError(Exception):
    """Un verrou est absent, périmé ou invalide."""


# --- source ------------------------------------------------------------------------------------


def load_pyproject(path: Path = PYPROJECT) -> dict:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def source_requirements(pyproject: dict, target: Target) -> list[str]:
    """Exigences directes (chaînes PEP 508) qui entrent dans le verrou de ``target``."""
    project = pyproject.get("project", {})
    requirements: list[str] = []
    if target.project_deps:
        requirements += list(project.get("dependencies", []))
    optional = project.get("optional-dependencies", {})
    for extra in target.extras:
        if extra not in optional:
            raise LockError(f"extra « {extra} » absent de pyproject.toml (cible {target.name})")
        requirements += list(optional[extra])
    groups = pyproject.get("dependency-groups", {})
    for group in target.groups:
        if group not in groups:
            raise LockError(f"groupe « {group} » absent de pyproject.toml (cible {target.name})")
        for item in groups[group]:
            if not isinstance(item, str):
                raise LockError(f"groupe « {group} » : inclusion de groupe non gérée ({item!r})")
            requirements.append(item)
    return requirements


def source_fingerprint(pyproject: dict, target: Target, exclude_newer: str) -> str:
    """Empreinte SHA-256 de tout ce qui détermine le verrou (source déclarative + paramètres)."""
    payload = {
        "target": target.name,
        "requires-python": pyproject.get("project", {}).get("requires-python"),
        "python-version": target.python_version,
        "requirements": sorted(source_requirements(pyproject, target)),
        "exclude-newer": exclude_newer,
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


# --- lecture d'un verrou -----------------------------------------------------------------------

_ENTRY = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?P<extras>\[[^\]]*\])?==(?P<version>[^\s;\\]+)(?P<rest>.*)$"
)


@dataclass
class LockEntry:
    name: str
    version: str
    marker: str | None
    hashes: list[str] = field(default_factory=list)


@dataclass
class Lock:
    headers: dict[str, str]
    entries: list[LockEntry]


def parse_lock(text: str) -> Lock:
    headers: dict[str, str] = {}
    entries: list[LockEntry] = []
    current: LockEntry | None = None
    if not text.startswith(HEADER_TAG):
        raise LockError("en-tête « GENERATED by scripts/locks.py » absent (fichier modifié à la main ?)")
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            match = re.match(r"#\s*([a-z0-9-]+):\s*(.*)$", line)
            if match:
                headers[match.group(1)] = match.group(2)
            continue
        if line.startswith("--hash=sha256:"):
            if current is None:
                raise LockError(f"empreinte orpheline : {line}")
            current.hashes.append(line.split("=", 1)[1].rstrip(" \\"))
            continue
        # Entrée « nom==version ; marqueur \ »
        line = line.rstrip("\\").strip()
        match = _ENTRY.match(line)
        if not match:
            raise LockError(f"ligne non épinglée « == » ou illisible : {line!r}")
        rest = match.group("rest").strip()
        marker = rest[1:].strip() if rest.startswith(";") else None
        current = LockEntry(canonicalize_name(match.group("name")), match.group("version"), marker or None)
        entries.append(current)
    return Lock(headers, entries)


def _specifier_satisfied(requirement: Requirement, entries: list[LockEntry]) -> str | None:
    """None si le verrou satisfait ``requirement``, sinon la raison."""
    name = canonicalize_name(requirement.name)
    candidates = [e for e in entries if e.name == name]
    if not candidates:
        return f"{requirement.name} absent du verrou"
    exact = any(op.operator == "==" for op in requirement.specifier)
    versions = [Version(e.version) for e in candidates]
    ok = [v for v in versions if requirement.specifier.contains(v, prereleases=True)]
    if not ok:
        return f"{requirement.name}: versions verrouillées {sorted(str(v) for v in versions)} hors de « {requirement.specifier} »"
    if exact and len(ok) != len(versions):
        return f"{requirement.name}: une version verrouillée ne respecte pas « {requirement.specifier} »"
    return None


def check_target(target: Target, pyproject: dict, lock_dir: Path = LOCK_DIR) -> list[str]:
    """Liste des écarts (vide = verrou cohérent avec la source). Hors ligne."""
    path = lock_dir / f"{target.name}.txt"
    if not path.is_file():
        return [f"{path.name}: verrou absent (python scripts/locks.py generate)"]
    problems: list[str] = []
    try:
        lock = parse_lock(path.read_text(encoding="utf-8"))
    except LockError as exc:
        return [f"{path.name}: {exc}"]

    exclude_newer = lock.headers.get("exclude-newer", "")
    expected = source_fingerprint(pyproject, target, exclude_newer)
    if lock.headers.get("target") != target.name:
        problems.append(f"{path.name}: cible déclarée « {lock.headers.get('target')} » ≠ « {target.name} »")
    if lock.headers.get("source-sha256") != expected:
        problems.append(
            f"{path.name}: DÉRIVE — la source (pyproject.toml) a changé depuis la génération du verrou "
            "(relancer : python scripts/locks.py generate)"
        )
    if not lock.entries:
        problems.append(f"{path.name}: aucune entrée")
    for entry in lock.entries:
        if not entry.hashes:
            problems.append(f"{path.name}: {entry.name}=={entry.version} sans empreinte sha256")
        if entry.marker:
            try:
                Marker(entry.marker)
            except Exception:  # noqa: BLE001 - toute erreur de marqueur est un verrou invalide
                problems.append(f"{path.name}: marqueur illisible pour {entry.name}: {entry.marker!r}")

    for raw in source_requirements(pyproject, target):
        try:
            requirement = Requirement(raw)
        except InvalidRequirement as exc:
            problems.append(f"pyproject.toml: exigence invalide {raw!r} ({exc})")
            continue
        reason = _specifier_satisfied(requirement, lock.entries)
        if reason:
            problems.append(f"{path.name}: {reason}")
    return problems


# --- génération --------------------------------------------------------------------------------


def _uv() -> str:
    uv = shutil.which("uv")
    if not uv:
        raise LockError("uv introuvable (pip install uv) : requis pour generate / --recompile")
    return uv


def _uv_version(uv: str) -> str:
    out = subprocess.run([uv, "--version"], capture_output=True, text=True, check=True).stdout.strip()
    return out.replace("uv ", "")


def compile_target(target: Target, pyproject_path: Path, out: Path, exclude_newer: str) -> None:
    """Résout ``target`` et écrit le verrou dans ``out`` (en-tête compris)."""
    uv = _uv()
    pyproject = load_pyproject(pyproject_path)
    command = [
        uv,
        "pip",
        "compile",
        "--universal",
        "--generate-hashes",
        "--no-header",
        "--no-annotate",
        "--python-version",
        target.python_version,
        "--exclude-newer",
        exclude_newer,
        "--quiet",
    ]
    command += ["--no-emit-package", "pip"]  # jamais d'outil de bootstrap dans un verrou
    with tempfile.TemporaryDirectory(prefix="locks-in-") as folder:
        in_file = Path(folder) / f"{target.name}.in"
        requirements = source_requirements(pyproject, target)
        in_file.write_text("\n".join(requirements) + "\n", encoding="utf-8")
        command += [str(in_file)]
        # La source déclarative reste pyproject.toml : le .in n'en est que la projection exacte.
        result = subprocess.run(command, capture_output=True, text=True, cwd=pyproject_path.parent)
        if result.returncode != 0:
            raise LockError(f"uv pip compile a échoué pour {target.name} (code {result.returncode}):\n{result.stderr}")
    header = "\n".join(
        [
            f"{HEADER_TAG} — ne pas éditer à la main.",
            f"# target: {target.name}",
            f"# description: {target.description}",
            f"# source-sha256: {source_fingerprint(pyproject, target, exclude_newer)}",
            f"# exclude-newer: {exclude_newer}",
            f"# uv: {_uv_version(uv)}",
            "# regenerate: python scripts/locks.py generate",
            "# install: pip install --require-hashes --no-deps -r <ce fichier>",
            "",
        ]
    )
    out.write_text(header + result.stdout, encoding="utf-8")


def generate(targets: list[Target], exclude_newer: str, lock_dir: Path = LOCK_DIR) -> None:
    lock_dir.mkdir(exist_ok=True)
    for target in targets:
        print(f"[locks] résolution de {target.name} …", flush=True)
        compile_target(target, PYPROJECT, lock_dir / f"{target.name}.txt", exclude_newer)
    write_requirements()


def write_requirements() -> None:
    for filename, target in REQUIREMENTS_FILES.items():
        (ROOT / filename).write_text(
            f"{HEADER_TAG} — ne pas éditer à la main.\n"
            "# La source des dépendances est pyproject.toml ; ce fichier inclut seulement le verrou haché.\n"
            f"# Installation : pip install --require-hashes --no-deps -r {filename}\n"
            f"-r locks/{target}.txt\n",
            encoding="utf-8",
        )


def recompile_diffs(targets: list[Target]) -> list[str]:
    """Compare chaque verrou à une résolution fraîche (même source, même date de gel)."""
    problems: list[str] = []
    for target in targets:
        path = LOCK_DIR / f"{target.name}.txt"
        if not path.is_file():
            problems.append(f"{path.name}: verrou absent")
            continue
        committed = path.read_text(encoding="utf-8")
        exclude_newer = parse_lock(committed).headers.get("exclude-newer", DEFAULT_EXCLUDE_NEWER)
        with tempfile.TemporaryDirectory(prefix="locks-out-") as folder:
            fresh = Path(folder) / path.name
            compile_target(target, PYPROJECT, fresh, exclude_newer)
            fresh_text = fresh.read_text(encoding="utf-8")

        def strip(text: str) -> list[str]:
            return [line for line in text.splitlines() if not line.startswith("# uv:")]

        if strip(committed) != strip(fresh_text):
            problems.append(f"{path.name}: diffère d'une résolution fraîche à la date de gel {exclude_newer}")
    return problems


def check_requirements_files() -> list[str]:
    problems = []
    for filename, target in REQUIREMENTS_FILES.items():
        path = ROOT / filename
        wanted = f"-r locks/{target}.txt"
        lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()] if path.is_file() else []
        active = [line for line in lines if line and not line.startswith("#")]
        if active != [wanted]:
            problems.append(f"{filename}: doit contenir uniquement « {wanted} » (python scripts/locks.py requirements)")
    return problems


# --- CLI ---------------------------------------------------------------------------------------


def _select(names: list[str]) -> list[Target]:
    if not names:
        return list(TARGETS.values())
    unknown = [n for n in names if n not in TARGETS]
    if unknown:
        raise LockError(f"cibles inconnues : {', '.join(unknown)} (disponibles : {', '.join(TARGETS)})")
    return [TARGETS[n] for n in names]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate", help="résout et réécrit les verrous (réseau + uv)")
    gen.add_argument("targets", nargs="*")
    gen.add_argument("--exclude-newer", default=DEFAULT_EXCLUDE_NEWER)
    chk = sub.add_parser("check", help="vérifie les verrous contre pyproject.toml (hors ligne)")
    chk.add_argument("targets", nargs="*")
    chk.add_argument("--recompile", action="store_true", help="compare aussi à une résolution fraîche (réseau + uv)")
    sub.add_parser("requirements", help="réécrit requirements*.txt")
    args = parser.parse_args(argv)

    try:
        if args.command == "generate":
            generate(_select(args.targets), args.exclude_newer)
            print("[locks] verrous écrits.")
            return 0
        if args.command == "requirements":
            write_requirements()
            return 0
        pyproject = load_pyproject()
        problems: list[str] = []
        targets = _select(args.targets)
        for target in targets:
            problems += check_target(target, pyproject)
        problems += check_requirements_files()
        if args.recompile and not problems:
            problems += recompile_diffs(targets)
    except LockError as exc:
        print(f"::error::{exc}")
        return 1
    if problems:
        for problem in problems:
            print(f"::error::{problem}")
        return 1
    print(f"[locks] {len(targets)} verrou(s) cohérent(s) avec pyproject.toml.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
